version: '3.8'
services:
  jax-server:
    image: clipseg:v1
    restart: always
    shm_size: '1gb'
    ports:
      - 8888:8888
    volumes:
      - .:/home
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
